[build]
  command = "npm install -g pnpm && pnpm install && PORT=3000 BASE_PATH=/ pnpm --filter @workspace/antonio-portfolio run build"
  publish = "artifacts/antonio-portfolio/dist/public"
  base = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
